services:
  azcgs-document:
    container_name: azcgs-document
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/document-3.0
    environment:
        - EULA=accept
        - billing=${FORM_RECOGNIZER_ENDPOINT_URI}
        - apiKey=${FORM_RECOGNIZER_KEY}
        - AzureCognitiveServiceLayoutHost=http://azcgs-layout:5000
    ports:
      - "5000:5050"
  azcgs-layout:
    container_name: azcgs-layout
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/layout-3.0
    environment:
        - EULA=accept
        - billing=${FORM_RECOGNIZER_ENDPOINT_URI}
        - apiKey=${FORM_RECOGNIZER_KEY}