services:
  azfr-layout:
    container_name: azfr-layout
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/layout-3.1
    environment:
      - EULA=accept
      - billing=${FORM_RECOGNIZER_ENDPOINT_URI}
      - apiKey=${FORM_RECOGNIZER_KEY}
    ports:
      - "5000:5000"
#     networks:
#       - docint

# networks:
#   docint:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.40.0.0/24
#           gateway: 172.40.0.1